name: nodejs-ci

on:
  push:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use latest Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true

    - name: Install modules
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test:ci
    
    - name: Lint
      run: npm run lint
