name: NodeJS CI

on:
  push:
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # abort running jobs if newer version is detected on same branch
    concurrency:
      group: ${{ github.head_ref || github.ref }}
      cancel-in-progress: true

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Use latest Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Install modules
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:ci
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379

      - name: Lint
        run: yarn lint
